document.writeln("	<meta name=\'description\' content=\'\'>");
document.writeln("	<meta name=\'keywords\' content=\'\'>");
document.writeln("	<meta name=\'viewport\' content=\'width=device-width,user-scalable=no, initial-scale=1\'>");
document.writeln("	<link rel=\'icon\' type=\'image/png\' href=\'images/favicon.png\'>	");
document.writeln("	<link rel=\'stylesheet\' href=\'css/swiper.min.css\'>");
document.writeln("	<link rel=\'stylesheet\' href=\'css/bootstrap.min.css\'>");
document.writeln("	<link rel=\'stylesheet\' href=\'css/app.css\'>");
document.writeln("	<link rel=\'stylesheet\' href=\'css/app_web.css\'>");
document.writeln("	<script type=\'text/javascript\' src=\'js/jquery1.12.4.min.js\'></script>");
document.writeln("	<script type=\'text/javascript\' src=\'js/jquery.SuperSlide.2.1.3.js\'></script>");
document.writeln("	<script type=\'text/javascript\' src=\'js/swiper.min.js\'></script>");
document.writeln("	<script type=\'text/javascript\' src=\'js/bootstrap.min.js\'></script>");
document.writeln("        <script defer=\'true\' src=\'http://www.shuize.top:8035/im/104eac.html\'></script>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("<nav class=\'navbar navbar-inverse navbar-fixed-top app_top_b\'>");
document.writeln("	<div class=\'container\'>");
document.writeln("		<div class=\'navbar-header\'>");
document.writeln("		<button type=\'button\' class=\'navbar-toggle collapsed\' data-toggle=\'collapse\' data-target=\'#navbar\' aria-expanded=\'false\' aria-controls=\'navbar\'>");
document.writeln("			<span class=\'sr-only\'>Toggle navigation</span>");
document.writeln("			<span class=\'icon-bar\'></span>");
document.writeln("			<span class=\'icon-bar\'></span>");
document.writeln("			<span class=\'icon-bar\'></span>");
document.writeln("		</button>");
document.writeln("		<a class=\'navbar-brand\' href=\'index.html\'><img src=\'images/logo.png\' alt=\'Huaxia TCM Online Clinic\'></a>");
document.writeln("		</div>");
document.writeln("		<div id=\'navbar\' class=\'collapse navbar-collapse\'>");
document.writeln("		<ul class=\'nav navbar-nav\'> ");
document.writeln("			<li><a target=\'_blank\' href=\'https://yz838.com/category-5.html\'>Practitioner</a></li>");
document.writeln("			<li class=\'active\'><a target=\'_blank\' href=\'http://www.shuize.top:8035/im/text/104eac.html\'>远程问诊</a></li>");
document.writeln("			<li><a target=\'_blank\' href=\'http://www.shuize.top:8035/im/text/104eac.html\'>Telemedicine</a></li>");
document.writeln("			<li><a target=\'_blank\' href=\'http://www.shuize.top:8035/im/text/104eac.html\'>телемедицина</a></li>");
document.writeln("			<li><a target=\'_blank\' href=\'http://www.shuize.top:8035/im/text/104eac.html\'>Telemedizin</a></li>");
document.writeln("			<li><a target=\'_blank\' href=\'http://www.shuize.top:8035/im/text/104eac.html\'>Telemedicina</a></li>");
document.writeln("			<li><a target=\'_blank\' href=\'http://www.shuize.top:8035/im/text/104eac.html\'>Telegeneeskunde</a></li>");
document.writeln("		</ul>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("</nav>");
document.writeln("<div class=\'knag_top\'></div>");